#!/bin/bash

# /Applications/VLC.app/Contents/MacOS/VLC --vlm-conf mosaic.vlm
/Applications/VLC.app/Contents/MacOS/VLC --vlm-conf mosaic.vlm --mosaic-width=1280 --mosaic-height=960 --mosaic-keep-picture --mosaic-rows=2 --mosaic-cols=2 --mosaic-position=1 --mosaic-order=1,2,3,4
